DROP TABLE PRODUCTS;
CREATE TABLE PRODUCTS (PRODUCTID Integer not null PRIMARY KEY, ARTICLE_ID Integer NOT NULL,
			ARTICLE_NAME varchar(255) NOT NULL, Price double NOT NULL,
			PRODUCT_FAMILY_ID Integer, PRODUCTFAMILYNAME varchar(255) NOT NULL,
			CATEGORY_ID Integer NOT NULL, CATEGORYNAME varchar(255) NOT NULL,
			GROUP_ID Integer NOT NULL, GROUPNAME varchar(255) NOT NULL,
			DAY Integer, MONTH Integer, YEAR Integer, 
			SHOPNAME varchar(255), NUMBER Integer, SALES double); 


DROP TABLE PLACES;
CREATE TABLE PLACES (PLACEID Integer not null PRIMARY KEY,
			LAND_ID Integer NOT NULL, LANDNAME varchar(255) NOT NULL,
			REGIONID Integer, REGIONNAME varchar(255) NOT NULL,
			CITYID Integer NOT NULL, CITYNAME varchar(255) NOT NULL,
			SHOP varchar(255) NOT NULL,
			DAY Integer, MONTH Integer, YEAR Integer, 
			ARTICLEID Integer NOT NULL, ARTICLENAME varchar(255),
			SHOPNAME varchar(255), NUMBER Integer, SALES double); 
